# permissions for end users to edit csiaddonscronjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csiaddonscronjob-editor-role
rules:
- apiGroups:
  - csiaddons.openshift.io
  resources:
  - csiaddonscronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - csiaddons.openshift.io
  resources:
  - csiaddonscronjobs/status
  verbs:
  - get
