# permissions for end users to edit csiaddonsjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csiaddonsjob-editor-role
rules:
- apiGroups:
  - csiaddons.openshift.io
  resources:
  - csiaddonsjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - csiaddons.openshift.io
  resources:
  - csiaddonsjobs/status
  verbs:
  - get
