# permissions for end users to view csiaddonscronjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csiaddonscronjob-viewer-role
rules:
- apiGroups:
  - csiaddons.openshift.io
  resources:
  - csiaddonscronjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - csiaddons.openshift.io
  resources:
  - csiaddonscronjobs/status
  verbs:
  - get
