# permissions for end users to view csiaddonsjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csiaddonsjob-viewer-role
rules:
- apiGroups:
  - csiaddons.openshift.io
  resources:
  - csiaddonsjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - csiaddons.openshift.io
  resources:
  - csiaddonsjobs/status
  verbs:
  - get
