// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIAddonsCronJob) DeepCopyInto(out *CSIAddonsCronJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIAddonsCronJob.
func (in *CSIAddonsCronJob) DeepCopy() *CSIAddonsCronJob {
	if in == nil {
		return nil
	}
	out := new(CSIAddonsCronJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CSIAddonsCronJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIAddonsCronJobList) DeepCopyInto(out *CSIAddonsCronJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CSIAddonsCronJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIAddonsCronJobList.
func (in *CSIAddonsCronJobList) DeepCopy() *CSIAddonsCronJobList {
	if in == nil {
		return nil
	}
	out := new(CSIAddonsCronJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CSIAddonsCronJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIAddonsCronJobSpec) DeepCopyInto(out *CSIAddonsCronJobSpec) {
	*out = *in
	out.JobSpec = in.JobSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIAddonsCronJobSpec.
func (in *CSIAddonsCronJobSpec) DeepCopy() *CSIAddonsCronJobSpec {
	if in == nil {
		return nil
	}
	out := new(CSIAddonsCronJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIAddonsCronJobStatus) DeepCopyInto(out *CSIAddonsCronJobStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIAddonsCronJobStatus.
func (in *CSIAddonsCronJobStatus) DeepCopy() *CSIAddonsCronJobStatus {
	if in == nil {
		return nil
	}
	out := new(CSIAddonsCronJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIAddonsJob) DeepCopyInto(out *CSIAddonsJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIAddonsJob.
func (in *CSIAddonsJob) DeepCopy() *CSIAddonsJob {
	if in == nil {
		return nil
	}
	out := new(CSIAddonsJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CSIAddonsJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIAddonsJobList) DeepCopyInto(out *CSIAddonsJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CSIAddonsJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIAddonsJobList.
func (in *CSIAddonsJobList) DeepCopy() *CSIAddonsJobList {
	if in == nil {
		return nil
	}
	out := new(CSIAddonsJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CSIAddonsJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIAddonsJobSpec) DeepCopyInto(out *CSIAddonsJobSpec) {
	*out = *in
	out.Operation = in.Operation
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIAddonsJobSpec.
func (in *CSIAddonsJobSpec) DeepCopy() *CSIAddonsJobSpec {
	if in == nil {
		return nil
	}
	out := new(CSIAddonsJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIAddonsJobStatus) DeepCopyInto(out *CSIAddonsJobStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIAddonsJobStatus.
func (in *CSIAddonsJobStatus) DeepCopy() *CSIAddonsJobStatus {
	if in == nil {
		return nil
	}
	out := new(CSIAddonsJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationSpec) DeepCopyInto(out *OperationSpec) {
	*out = *in
	out.SpaceReclaim = in.SpaceReclaim
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationSpec.
func (in *OperationSpec) DeepCopy() *OperationSpec {
	if in == nil {
		return nil
	}
	out := new(OperationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpaceReclaimSpec) DeepCopyInto(out *SpaceReclaimSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpaceReclaimSpec.
func (in *SpaceReclaimSpec) DeepCopy() *SpaceReclaimSpec {
	if in == nil {
		return nil
	}
	out := new(SpaceReclaimSpec)
	in.DeepCopyInto(out)
	return out
}
